# Generated by Django 4.0.4 on 2022-05-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_cartorder_cartorderitemms'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cartorderitemms',
            name='order',
        ),
        migrations.DeleteModel(
            name='CartOrder',
        ),
        migrations.DeleteModel(
            name='CartOrderItemms',
        ),
    ]
